<?php

namespace ListBroking\AppBundle\Repository;

use ListBroking\AppBundle\Model\AudiencesFilter;

/**
 * AudiencesStatsRepositoryInterface
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface AudiencesStatsRepositoryInterface
{
    /**
     * Eliminates all data
     */
    public function truncate(): void;

    /**
     * Get audiences with the given minimum resting date
     *
     * @param string $minimumRestingDate
     */
    public function updateStats(string $minimumRestingDate): void;

    /**
     * Get Audiences for the given filter
     *
     * @param AudiencesFilter $filter
     *
     * @return array
     */
    public function getAudiences(AudiencesFilter $filter): array;
}
