<?php

namespace ListBroking\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Intl\Exception\MethodNotImplementedException;

/**
 * ContactHistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactHistRepository extends EntityRepository implements ContactRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function findByEmail(string $email): array
    {
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('ch')
                    ->from('ListBrokingAppBundle:ContactHist', 'ch')
                    ->where('ch.email = :email')
                    ->setParameter('email', $email)
                    ->getQuery()
                    ->getResult();
    }

    /**
     * {@inheritdoc}
     */
    public function findByIdAndLead($id, int $leadId)
    {
        throw new MethodNotImplementedException();
    }

    /**
     * {@inheritdoc}
     */
    public function findByLeadAndEmailAndOwner(int $leadId, string $email, string $owner)
    {
        throw new MethodNotImplementedException();
    }
}
