<?php

namespace ListBroking\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LeadHistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadHistRepository extends EntityRepository implements LeadRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function getByPhone(string $phone): array
    {
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('lh')
                    ->from('ListBrokingAppBundle:LeadHist', 'lh')
                    ->where('lh.phone = :phone')
                    ->setParameter('phone', $phone)
                    ->getQuery()
                    ->getResult();
    }
}
