last_exceptions:
    path: /ajax/exception/last
    defaults: { _controller: ListBrokingAppBundle:Ajax:lastExceptions }
    options:
        expose: true

ajax_lead_count:
    path: /ajax/lead/count
    defaults: { _controller: ListBrokingAppBundle:Ajax:countLeads }
    options:
        expose: true

ajax_form_lists:
    path: /ajax/form/lists
    defaults: { _controller: ListBrokingAppBundle:Ajax:lists }
    options:
        expose: true

ajax_form_submit:
    path: /ajax/form/submit/{form_name}
    defaults: { _controller: ListBrokingAppBundle:Ajax:formSubmission }
    options:

ajax_extraction_contacts:
    path: /ajax/extraction/{extraction_id}/contacts
    defaults: { _controller: ListBrokingAppBundle:Ajax:extractionContacts }
    options:
        expose: true
    requirements:
          extraction_id: \d+

ajax_extraction_exclude_lead:
    path: /ajax/extraction/{extraction_id}/lead/{lead_id}/exclude
    defaults: { _controller: ListBrokingAppBundle:Ajax:extractionExcludeLead }
    options:
        expose: true
    requirements:
          extraction_id: \d+
          lead_id: \d+

ajax_extraction_download:
    path: /ajax/extraction/{extraction_id}/download/{extraction_template_id}
    defaults: { _controller: ListBrokingAppBundle:Ajax:extractionDownload }
    options:
        expose: true

ajax_extraction_locks:
    path: /ajax/extraction/{extraction_id}/locks
    defaults: { _controller: ListBrokingAppBundle:Ajax:extractionLocks }
    options:
        expose: true

ajax_extraction_deliver:
    path: /ajax/extraction/{extraction_id}/deliver/{extraction_template_id}
    defaults: { _controller: ListBrokingAppBundle:Ajax:extractionDeliver }
    options:
        expose: true

ajax_deduplication:
    path: /ajax/extraction/{extraction_id}/deduplication
    defaults: { _controller: ListBrokingAppBundle:Ajax:deduplication }
    options:
        expose: true

ajax_deduplication_queue:
    path: /ajax/extraction/{extraction_id}/deduplication/queue
    defaults: { _controller: ListBrokingAppBundle:Ajax:deduplicationQueue }
    options:
        expose: true

api_create_lead:
    path:     /v1/lead/create
    defaults: { _controller: ListBrokingAppBundle:API:createStagingLead }
#    methods:  [POST]

list_broking_upload_test:
    path:     /leads/upload
    defaults: { _controller: ListBrokingAPIBundle:Default:testUpload }