imports:
    - { resource: admin_services.yml }

services:
  listbroking.flush_listener:
    class: ListBroking\AppBundle\EventListener\FlushListener
    arguments: [@doctrine_cache.providers.memcached_query_cache]
    tags:
        - { name: doctrine.event_listener, event: onFlush }

  listbroking.appbundle.filters.form:
    class:  ListBroking\AppBundle\Form\FiltersForm
    arguments: [@app]
    tags:
      - { name: form.type, alias: filters }

  listbroking.appbundle.json.form.type:
    class: ListBroking\AppBundle\Form\Type\JsonType
    tags:
      - { name: form.type, alias: json }

  guzzle.client:
      class: %guzzle.client.class%
      tags:
          - { name: "guzzle.client" }
  base:
    class: ListBroking\AppBundle\Service\Base\BaseService
    abstract: true
    calls:
      - [setLogger, [@logger]]
      - [setDoctrine, [@doctrine]]
      - [setEntityManager, [@doctrine.orm.entity_manager]]
      - [setCache, [@doctrine_cache.providers.memcached_query_cache]]
      - [setFormFactory, [@form.factory]]

  app:
    class: ListBroking\AppBundle\Service\Helper\AppService
    parent: base

  lead:
    class: ListBroking\AppBundle\Service\BusinessLogic\LeadService
    arguments:
      entityManager: @doctrine.orm.entity_manager

  extraction:
    class: ListBroking\AppBundle\Service\BusinessLogic\ExtractionService
    parent: base
    arguments: [@request_stack, @filter_engine, @mailer, @twig ]

  staging:
    class: ListBroking\AppBundle\Service\BusinessLogic\StagingService
    parent: base
    arguments: [@validator_engine]

  filter_engine:
    class: ListBroking\AppBundle\Engine\FilterEngine
    arguments:
      entityManager: @doctrine.orm.entity_manager

  validator_engine:
    class: ListBroking\AppBundle\Engine\ValidatorEngine
    parent: base
    arguments: [@guzzle.client]