imports:
    - { resource: admin_services.yml }

services:
  listbroking.appbundle.filters.form:
    class:  ListBroking\AppBundle\Form\FiltersForm
    arguments: [@app, @lead]
    tags:
      - { name: form.type, alias: filters }

  listbroking.appbundle.json.form.type:
    class: ListBroking\AppBundle\Form\Type\JsonType
    tags:
      - { name: form.type, alias: json }

  filter_engine:
    class: ListBroking\AppBundle\Engine\FilterEngine
    arguments:
      entityManager: @doctrine.orm.entity_manager

  app:
    class: ListBroking\AppBundle\Service\AppService
    arguments:
      entityManager: @doctrine.orm.entity_manager
      doctrineCache: @doctrine_cache.providers.apc_query_cache

  lead:
    class: ListBroking\AppBundle\Service\LeadService
    arguments:
      entityManager: @doctrine.orm.entity_manager

  extraction:
    class: ListBroking\AppBundle\Service\ExtractionService
    arguments:
      entityManager: @doctrine.orm.entity_manager
      doctrineCache: @doctrine_cache.providers.apc_query_cache
      requestStack: @request_stack
      session: @session
      formFactory: @form.factory
      phpExcel: @phpexcel
      filterEngine: @filter_engine
  ui:
    class: ListBroking\AppBundle\Service\UIService
    arguments:
      - @app
      - @extraction
      - @lead
      - @form.factory
      - @security.csrf.token_manager
      - @doctrine.orm.entity_manager
