imports:
    - { resource: services/listener.yml }
    - { resource: services/monolog.yml }
    - { resource: services/form.yml }
    - { resource: services/base.yml }
    - { resource: services/service.yml }
    - { resource: services/consumer.yml }
    - { resource: services/admin.yml }
    - { resource: services/factory.yml }
    - { resource: services/controller.yml }
    - { resource: services/validation.yml }
    - { resource: services/repository.yml }
