ListBroking\LockBundle\Entity\Lock:
    type: entity
    table: lb_lock
    id:
        id:
            type: bigint
            id: true
            generator:
                strategy: AUTO
    fields:
        is_active:
            type: boolean
            column: is_active
            nullable: true
            options:
                default: 0
        status:
            type: smallint
            column: status
        type:
            type: smallint
            column: type
        expiration_date:
            type: datetime
            column: expiration_date
# Timestampable
        created_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: create } }

        updated_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: update } }
# End of Timestampable
    manyToOne:
        client:
            targetEntity: ListBroking\ClientBundle\Entity\Client
            joinColumn:
                name:     client_id
                referencedColumnName: id
                onDelete: restrict
                nullable: true
        lead:
            targetEntity: ListBroking\LeadBundle\Entity\Lead
            inversedBy: locks
            joinColumn:
                name:     lead_id
                referencedColumnName: id
                onDelete: restrict
        campaign:
            targetEntity: ListBroking\ClientBundle\Entity\Campaign
            joinColumn:
                name:     campaign_id
                referencedColumnName: id
                onDelete: restrict
                nullable: true
        category:
            targetEntity: ListBroking\CoreBundle\Entity\Category
            joinColumn:
                name:     category_id
                referencedColumnName: id
                onDelete: restrict
                nullable: true
        sub_category:
            targetEntity: ListBroking\CoreBundle\Entity\SubCategory
            joinColumn:
                name:     sub_category_id
                referencedColumnName: id
                onDelete: restrict
                nullable: true