<?php

namespace ListBroking\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactCampaignHistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactCampaignHistRepository extends EntityRepository implements ContactCampaignHistRepositoryInterface
{
}
