<?php

namespace ListBroking\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactCampaignHistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactCampaignHistRepository extends EntityRepository implements ContactCampaignRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function generateHistory(int $extractionId): void
    {
        $connection = $this->getEntityManager()
                           ->getConnection();

        $query = 'INSERT INTO contact_campaign_hist (contact_id, campaign_id, created_at)
                    SELECT ech.contact_id, ex.campaign_id, now()
                    FROM extraction_contact_hist ech
                    JOIN extraction ex ON ex.id=ech.extraction_id
                    WHERE ech.extraction_id = :extraction_id';

        $statement = $connection->prepare($query);
        $statement->execute(
            [
                'extraction_id' => $extractionId,
            ]
        );
    }
}
