ListBroking\TaskControllerBundle\Entity\Task:
    type: entity
    table: task
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 75
        status:
            type: string
            length: 15
        pid:
            type: integer
        msg:
            type: text
            nullable: true
# Timestampable
        created_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: create } }

        updated_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: update } }
# End of Timestampable
    lifecycleCallbacks: {  }
