
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      domain: %domain%
      logo:   'https://lb.globodigitalagency.com/bundles/listbrokingapp/images/logo.png'
