api_create_staging_lead:
    path: /v1/create/staging_lead
    defaults: { _controller: app.controller.api:createStagingLeadAction }

api_campaigns_get_active:
    path: /v1/campaigns/active
    defaults: { _controller: app.controller.api:getActiveCampaignsAction }

api_campaigns_get_revenue:
    path: /v1/campaigns/revenue
    defaults: { _controller: app.controller.api:getExtractionsRevenueAction }

api_contact_history:
    path: /v1/contact/history
    defaults: { _controller: app.controller.api:contactHistoryAction }
    methods: [GET]

api_contact_erase:
    path: /v1/contact/erasure
    defaults: { _controller: app.controller.api:contactErasureAction }
    methods: [POST]

api_campaign_creation:
    path: /v1/campaign
    defaults: { _controller: app.controller.api:createCampaignAction }
    methods: [POST]

api_get_audiences:
    path: /v1/audiences
    defaults: { _controller: app.controller.api:getAudiencesAction }
    methods: [GET]
