api_create_staging_lead:
    path: /v1/create/staging_lead
    defaults: { _controller: app.controller.api:createStagingLeadAction }

api_campaigns_get_active:
    path: /v1/campaigns/active
    defaults: { _controller: app.controller.api:getActiveCampaignsAction }

api_campaigns_get_revenue:
    path: /v1/campaigns/revenue
    defaults: { _controller: app.controller.api:getExtractionsRevenueAction }

api_contact_history:
    path: /v1/contact/history
    defaults: { _controller: app.controller.api:contactHistoryAction }
    methods: [GET]

api_contact_erase:
    path: /v1/contact/erasure
    defaults: { _controller: app.controller.api:contactErasureAction }
    methods: [POST]

api_campaign_creation:
    path: /v1/campaign
    defaults: { _controller: app.controller.api:createCampaignAction }
    methods: [POST]

api_extraction_creation:
    path: /v1/extraction
    defaults: { _controller: app.controller.api:createExtractionAction }
    methods: [POST]

api_extraction_close:
    path: /v1/extraction/{extraction_id}/close
    defaults: { _controller: app.controller.api:closeExtractionAction }
    methods: [PUT]

api_get_extraction_contacts:
    path: /v1/extraction/{extraction_id}/contacts
    defaults: { _controller: app.controller.api:getExtractionContactsAction }
    methods: [GET]

api_get_audiences:
    path: /v1/audiences
    defaults: { _controller: app.controller.api:getAudiencesAction }
    methods: [GET]

api_accept_consent_revalidation:
    path: /v1/consent_revalidation/{id}/accept
    defaults: { _controller: app.controller.api:acceptConsentRevalidation }
    methods: [PUT,POST]

api_reject_consent_revalidation:
    path: /v1/consent_revalidation/{id}/reject
    defaults: { _controller: app.controller.api:rejectConsentRevalidation }
    methods: [PUT,POST]