ajax_find_extraction:
    path: /ajax/extraction/{extraction_id}/find
    defaults: { _controller: ListBrokingAppBundle:AjaxExtraction:findExtraction }
    options:
        expose: true
    requirements:
          extraction_id: \d+

ajax_extraction_contacts:
    path: /ajax/extraction/{extraction_id}/contacts
    defaults: { _controller: ListBrokingAppBundle:AjaxExtraction:extractionPreview }
    options:
        expose: true
    requirements:
          extraction_id: \d+

ajax_extraction_summary:
    path: /ajax/extraction/{extraction_id}/summary
    defaults: { _controller: ListBrokingAppBundle:AjaxExtraction:extractionSummary }
    options:
        expose: true
    requirements:
          extraction_id: \d+

#ajax_extraction_exclude_lead:
#    path: /ajax/extraction/{extraction_id}/lead/{lead_id}/exclude
#    defaults: { _controller: ListBrokingAppBundle:AjaxExtraction:extractionExcludeLead }
#    options:
#        expose: true
#    requirements:
#          extraction_id: \d+
#          lead_id: \d+

ajax_extraction_download:
    path: /ajax/extraction/{extraction_id}/download/{extraction_template_id}
    defaults: { _controller: ListBrokingAppBundle:AjaxExtraction:extractionDownload }
    options:
        expose: true

ajax_extraction_locks:
    path: /ajax/extraction/{extraction_id}/locks
    defaults: { _controller: ListBrokingAppBundle:AjaxExtraction:extractionLocks }
    options:
        expose: true

ajax_extraction_deliver:
    path: /ajax/extraction/{extraction_id}/deliver/{extraction_template_id}
    defaults: { _controller: ListBrokingAppBundle:AjaxExtraction:extractionDeliver }
    options:
        expose: true

ajax_extraction_deduplication:
    path: /ajax/extraction/{extraction_id}/deduplication
    defaults: { _controller: ListBrokingAppBundle:AjaxExtraction:extractionDeduplication }
    options:
        expose: true

#ajax_deduplication_queue:
#    path: /ajax/extraction/{extraction_id}/deduplication/queue
#    defaults: { _controller: ListBrokingAppBundle:Ajax:deduplicationQueue }
#    options:
#        expose: true