ListBroking\AppBundle\Entity\Country:
    type: entity
    table: country
    id:
        id:
            type: bigint
            id:   true
            generator:
                strategy: AUTO
    fields:
        name:
            type:   string
            column: name
            unique: true
# Timestampable
        created_at:
            type:     datetime
            nullable: true
            gedmo:    { timestampable: { on: create } }

        updated_at:
            type:     datetime
            nullable: true
            gedmo:    { timestampable: { on: update } }
# End of Timestampable