ListBroking\AppBundle\Entity\ExtractionDeduplication:
    type: entity
    table: extraction_deduplication
    repositoryClass: ListBroking\AppBundle\Repository\ExtractionDeduplicationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        lead_index:
          columns: [ lead_id ]
        contact_index:
          columns: [ contact_id ]
        phone_index:
          columns: [ phone ]
    fields:
        lead_id:
            type: integer
            column: lead_id
            nullable: true
        contact_id:
            type: integer
            column: contact_id
            nullable: true
        phone:
            type:     string
            column:   phone
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo: { timestampable: { on: create } }
            options:
                default: 0
    manyToOne:
        extraction:
            targetEntity:             ListBroking\AppBundle\Entity\Extraction
            inversedBy:               extraction_deduplications
            joinColumn:
                name:                 extraction_id
                referencedColumnName: id
                onDelete:             restrict
    lifecycleCallbacks: {  }
