ListBroking\AppBundle\Entity\ExtractionDeduplication:
    type: entity
    table: extraction_deduplication
    repositoryClass: ListBroking\AppBundle\Repository\ExtractionDeduplicationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lead_id:
            type: integer
            column: lead_id
            nullable: true
        contact_id:
            type: integer
            column: contact_id
            nullable: true
        phone:
            type: integer
            column: phone
            nullable: true
        email:
            type: text
            column: email
            nullable: true

# Timestampable
        created_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: create } }

        updated_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: update } }
# End of Timestampable
# Blameable
    manyToOne:
        created_by:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: created_by
                referencedColumnName: id
                onDelete: restrict
            gedmo: { blameable: { on: create } }

        updated_by:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: updated_by
                referencedColumnName: id
                onDelete: restrict
            gedmo: { blameable: { on: update } }
# End of blameable
        extraction:
            targetEntity:             ListBroking\AppBundle\Entity\Extraction
            inversedBy:               extraction_deduplications
            joinColumn:
                name:                 extraction_id
                referencedColumnName: id
                onDelete:             restrict
            gedmo: { blameable: { on: create } }
    lifecycleCallbacks: {  }
