ListBroking\AppBundle\Entity\ExtractionDeduplication:
    type: entity
    table: extraction_deduplication
    repositoryClass: ListBroking\AppBundle\Repository\ExtractionDeduplicationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        phone_index:
          columns: [ phone ]
    fields:
        lead_id:
            type: integer
            column: lead_id
            nullable: true
        contact_id:
            type: integer
            column: contact_id
            nullable: true
        phone:
            type: integer
            column: phone
            nullable: true
    manyToOne:
        extraction:
            targetEntity:             ListBroking\AppBundle\Entity\Extraction
            inversedBy:               extraction_deduplications
            joinColumn:
                name:                 extraction_id
                referencedColumnName: id
                onDelete:             restrict
    lifecycleCallbacks: {  }