ListBroking\AppBundle\Entity\ExtractionDeduplication:
    type: entity
    table: extraction_deduplication
    repositoryClass: ListBroking\AppBundle\Repository\ExtractionDeduplicationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lead_id:
            type: integer
            column: lead_id
            nullable: true
        contact_id:
            type: integer
            column: contact_id
            nullable: true
        extraction_id:
            type: integer
            column: extraction_id
            nullable: true
        phone:
            type: integer
            column: phone
            nullable: true
        email:
            type: text
            column: email
            nullable: true
    lifecycleCallbacks: {  }