ListBroking\AppBundle\Entity\LockHistory:
    type: entity
    table: lb_lock_history
    id:
        id:
            type: bigint
            id: true
    fields:
        status:
            type: smallint
            column: status
        type:
            type: smallint
            column: type
        expiration_date:
            type: datetime
            column: expiration_date
# Timestampable
        created_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: create } }

        updated_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: update } }
# End of Timestampable
    manyToOne:
        client:
            targetEntity: ListBroking\AppBundle\Entity\Client
            joinColumn:
                name:     client_id
                referencedColumnName: id
                onDelete: restrict
                nullable: true
        lead:
            targetEntity: ListBroking\AppBundle\Entity\Lead
            joinColumn:
                name:     lead_id
                referencedColumnName: id
                onDelete: restrict
        campaign:
            targetEntity: ListBroking\AppBundle\Entity\Campaign
            joinColumn:
                name:     campaign_id
                referencedColumnName: id
                onDelete: restrict
                nullable: true
        category:
            targetEntity: ListBroking\AppBundle\Entity\Category
            joinColumn:
                name:     category_id
                referencedColumnName: id
                onDelete: restrict
                nullable: true
        sub_category:
            targetEntity: ListBroking\AppBundle\Entity\SubCategory
            joinColumn:
                name:     sub_category_id
                referencedColumnName: id
                onDelete: restrict
                nullable: true