ListBroking\AppBundle\Entity\Owner:
    type: entity
    table: owner
    id:
        id:
            type: bigint
            id:   true
            generator:
                strategy: AUTO
    fields:
        name:
            type:   string
            column: name
            unique: true
# Timestampable
        created_at:
            type:     datetime
            nullable: true
            gedmo:    { timestampable: { on: create } }

        updated_at:
            type:     datetime
            nullable: true
            gedmo:    { timestampable: { on: update } }
# End of Timestampable
    manyToOne:
        country:
            targetEntity: ListBroking\AppBundle\Entity\Country
            joinColumn:
                name:                 country_id
                referencedColumnName: id
                onDelete:             restrict
    oneToMany:
        sources:
            targetEntity: ListBroking\AppBundle\Entity\Source
            mappedBy:     owner
            cascade:      [all]
        contacts:
            targetEntity: ListBroking\AppBundle\Entity\Contact
            mappedBy:     owner
            cascade:      [all]
