services:
    aws_s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                version: latest
                region: %aws_s3_region%
                credentials:
                    key: %aws_s3_key%
                    secret: %aws_s3_secret%