list_broking_api_page:
    path:     /v1/lead/create
    defaults: { _controller: listbroking.api.lead.controller:setLeadAction }
    methods:  [POST]

list_broking_upload_test:
    path:     /leads/upload
    defaults: { _controller: ListBrokingAPIBundle:Default:testUpload }