ListBroking\ExceptionHandlerBundle\Entity\ExceptionLog:
    type: entity
    table: exception_log
    id:
        id:
            type: bigint
            generator: { strategy: AUTO }
    fields:
        code:
            type: string
        msg:
            type: text
        trace:
            type: text
# Timestampable
        created_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: create } }

        updated_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: update } }
# End of Timestampable