oneup_flysystem:
    adapters:
        aws_s3_adapter:
            awss3v3:
                client: aws_s3_client
                bucket: %aws_s3_bucket%
                prefix: ~
    filesystems:
        aws_s3:
            adapter: aws_s3_adapter
            cache: ~
            alias: ~
            mount: ~