monolog:
    handlers:
        service:
            type:   stream
            path:  "%kernel.logs_dir%/%kernel.environment%_service.log"
            level:  "%monolog.level.service%"
            formatter: adclick.logger.formatter.compactformat
            channels: ['service']
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%_main.log"
            level: "%monolog.level.main%"


