
# Swiftmailer Configuration
swiftmailer:
    encryption: "%mailer_encryption%"
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
        type: file
        path: "%kernel.root_dir%/spool"
