# Swiftmailer Configuration
swiftmailer:
  default_mailer: spool
  mailers:
    spool:
      transport:      '%mailer_transport%'
      encryption:     '%mailer_encryption%'
      host:           '%mailer_host%'
      port:           '%mailer_port%'
      sender_address: '%mailer_from_email%'
      username:       '%mailer_user%'
      password:       '%mailer_password%'
      spool: { type: memory }

    no_spool:
      transport:      '%mailer_transport%'
      encryption:     '%mailer_encryption%'
      host:           '%mailer_host%'
      port:           '%mailer_port%'
      sender_address: '%mailer_from_email%'
      username:       '%mailer_user%'
      password:       '%mailer_password%'
