imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine_cache.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ListBrokingAppBundle, FOSUserBundle ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
            apply_to: "\.css$"
        yui_js:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:    "%database_driver%"
        host:      "%database_host%"
        port:      "%database_port%"
        dbname:    "%database_name%"
        user:      "%database_user%"
        password:  "%database_password%"
        charset:   UTF8
        logging:   "%database_logging%"
        profiling: "%database_profiling%"
        types:
          json: Sonata\Doctrine\Types\JsonType

    orm:
#        metadata_cache_driver: apc
#        query_cache_driver: apc
#        result_cache_driver: apc
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            datetime_functions:
                interval: L

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:       "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

stof_doctrine_extensions:
  default_locale: en_UK
  class:
    blameable: ListBroking\AppBundle\EventListener\BlameableListener
  orm:
    default:
      timestampable: true
      blameable: true

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

fos_js_routing:
    cache_control:
        public: true

sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    impersonating:
        route: sonata_admin_dashboard
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
            contexts:   [admin]
        sonata.user.block.account: # used to display menu option (login option)
            contexts:   [admin]
        sonata.block.service.text: # used to if you plan to use Sonata user routes
            contexts:   [admin]
        sonata.admin.block.admin_list:
            contexts:   [admin]
        app.admin.statistics_block:
            contexts:   [admin]
        app.admin.operational_email:
            contexts:   [admin]
sonata_admin:
    options:
      title_mode: single_image
    title: ListBroking - Contact broking simplified
    title_logo: bundles/listbrokingapp/images/logo.png
    security:
        handler: sonata.admin.security.handler.acl
        information:
            STAFF:    [VIEW, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER, OWNER]
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    templates:
        layout: ListBrokingAppBundle::base.html.twig
    dashboard:
        blocks:
            -
              position: top
              type: app.admin.statistics_block
              class: col-md-12
            -
              position: top
              type: app.admin.operational_email
              class: col-md-12
    assets:
      stylesheets:

          # Defaults:
          - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
          - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
          - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
          - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
          - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
          - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css

          # Overrides
          - bundles/sonataadmin/vendor/select2/select2.css # OLD VERSION
          - bundles/sonataadmin/vendor/select2/select2-bootstrap.css # OLD VERSION
#          - bower/select2/dist/css/select2.min.css  # NEW VERSION
#          - bower/select2-bootstrap-css/select2-bootstrap.min.css # NEW VERSION


          # More Defaults:
          - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
          - bundles/sonataadmin/css/styles.css
          - bundles/sonataadmin/css/layout.css

          # Extra
          - bower/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css
          - bower/bootstrap-daterangepicker/daterangepicker-bs3.css
          - bower/jquery-file-upload/css/jquery.fileupload.css
          - bundles/listbrokingapp/css/000_global.css
          - bundles/listbrokingapp/css/001_fixed_columns.css
          - bundles/listbrokingapp/css/002_extraction.css

      javascripts:

        # Defaults:
        - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js

        # Overrides
#        - bundles/sonatacore/vendor/moment/min/moment.min.js # OLD VERSION - 2.6.0
        - bundles/sonataadmin/vendor/select2/select2.min.js # OLD VERSION - V3
        - bower/moment/min/moment.min.js # NEW VERSION - ~2.8.4
#        - bower/select2/dist/js/select2.min.js # NEW VERSION - V4

        # More Defaults:
        - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
        - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
        - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
        - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
        - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
        - bundles/sonataadmin/jquery/jquery.form.js
        - bundles/sonataadmin/jquery/jquery.confirmExit.js
        - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js

        # Extra
        - bower/bootstrap-daterangepicker/daterangepicker.js
        - bower/DataTables/media/js/jquery.dataTables.min.js
        - bower/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js
        - bower/jquery.inputmask/dist/inputmask/jquery.inputmask.js
        - bower/jquery.inputmask/dist/inputmask/jquery.inputmask.numeric.extensions.js
        - bower/jquery-file-upload/js/jquery.iframe-transport.js
        - bower/jquery-file-upload/js/jquery.fileupload.js
        - bower/jquery-file-upload/js/jquery.fileupload-process.js
        - bower/jquery-file-upload/js/jquery.fileupload-validate.js
        - bundles/fosjsrouting/js/router.js

        # More Defaults
        - bundles/sonataadmin/App.js
        - bundles/sonataadmin/Admin.js

        # More Extra
        - bundles/listbrokingapp/js/000_listbroking.js
        - bundles/listbrokingapp/js/001_global.js
        - bundles/listbrokingapp/js/002_tables.js
        - bundles/listbrokingapp/js/003_configuration.js
        - bundles/listbrokingapp/js/004_forms.js
        - bundles/listbrokingapp/js/005_collections.js
        - bundles/listbrokingapp/js/006_deduplication.js
        - bundles/listbrokingapp/js/007_confirm_extraction.js
        - bundles/listbrokingapp/js/008_opposition_list.js
        - bundles/listbrokingapp/js/009_staging_contact.js
        - bundles/listbrokingapp/js/999_lastJs.js