# Used to expose routing to the client-side code
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

app_bundle:
    resource: "@ListBrokingAppBundle/Resources/config/routing.yml"

root:
  path:   /
  defaults:
    _controller: FrameworkBundle:Redirect:urlRedirect
    path: /admin/dashboard
    permanent: true