list_broking_api:
    type:     rest
    prefix:   /api
    resource: "@ListBrokingAPIBundle/Resources/config/routing.yml"

list_broking_ui:
    resource: "@ListBrokingUIBundle/Resources/config/routing.yml"
    prefix:   /

adclick_user:
    resource: "@AdclickUserBundle/Resources/config/routing.yml"
    prefix:   /