base_routes:
    prefix:   /admin
    resource: "routing/base.yml"

ajax_routes:
    prefix:   /admin
    resource: "routing/ajax.yml"

ajax_extraction_routes:
    prefix:   /admin
    resource: "routing/ajax_extraction.yml"

api_routes:
    prefix:   /api
    resource: "routing/api.yml"

api_webhook_routes:
    prefix: /api/webhook
    resource: "routing/webhook.yml"