ListBroking\AppBundle\Entity\Client:
   constraints:
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
           fields:   name
           message:  "Name is duplicated."
ListBroking\AppBundle\Entity\Campaign:
   constraints:
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
           fields:   name
           message:  "Name is duplicated."

ListBroking\AppBundle\Entity\Country:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:   name
            message:  "Name is duplicated."

ListBroking\AppBundle\Entity\Category:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:   name
            message:  "Name is duplicated."

ListBroking\AppBundle\Entity\Extraction:
   constraints:
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
           fields:   name
           message:  "Name is duplicated."

ListBroking\AppBundle\Entity\Extraction:
   constraints:
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
           fields:   contacts
           message:  "Contact is duplicated."

ListBroking\AppBundle\Entity\OppositionList:
   constraints:
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
           fields:
              - type
              - phone
           message:  "Phone is duplicated for type"
