parameters:
    listbroking.corebundle.country.entity.name:  ListBrokingCoreBundle:Country
    listbroking.corebundle.country.entity.class: ListBroking\CoreBundle\Entity\Country
    listbroking.corebundle.country.repository.class: ListBroking\CoreBundle\Repository\ORM\CountryRepository

    listbroking.corebundle.category.entity.name:  ListBrokingCoreBundle:Category
    listbroking.corebundle.category.entity.class: ListBroking\CoreBundle\Entity\Category
    listbroking.corebundle.category.repository.class: ListBroking\CoreBundle\Repository\ORM\CategoryRepository

    listbroking.corebundle.subcategory.entity.name:  ListBrokingCoreBundle:SubCategory
    listbroking.corebundle.subcategory.entity.class: ListBroking\CoreBundle\Entity\SubCategory
    listbroking.corebundle.subcategory.repository.class: ListBroking\CoreBundle\Repository\ORM\SubCategoryRepository

services:
    listbroking.corebundle.country.repository:
        class: %listbroking.corebundle.country.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.corebundle.country.entity.name%
            alias: cbc
            entityClass: %listbroking.corebundle.country.entity.class%
            inflector: @inflector.tool
    listbroking.corebundle.category.repository:
        class: %listbroking.corebundle.category.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.corebundle.category.entity.name%
            alias: cbc
            entityClass: %listbroking.corebundle.category.entity.class%
            inflector: @inflector.tool
    listbroking.corebundle.subcategory.repository:
        class: %listbroking.corebundle.subcategory.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.corebundle.subcategory.entity.name%
            alias: cbc
            entityClass: %listbroking.corebundle.subcategory.entity.class%
            inflector: @inflector.tool
