ListBroking\CoreBundle\Entity\Country:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:   name
            message:  "Name is duplicated."
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:   iso_code
            message:  "Iso code is duplicated."