CREATE TABLE fos_user (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_957A647992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_957A6479A0D96FBF (email_canonical), INDEX IDX_957A6479DE12AB56 (created_by), INDEX IDX_957A647916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE fos_user_group (user_id BIGINT NOT NULL, group_id BIGINT NOT NULL, INDEX IDX_583D1F3EA76ED395 (user_id), INDEX IDX_583D1F3EFE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE fos_group (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_4B019DDB5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE api_token (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, name VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7BA2F5EB5E237E06 (name), INDEX IDX_7BA2F5EBDE12AB56 (created_by), INDEX IDX_7BA2F5EB16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE advanced_configuration (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, scope VARCHAR(255) DEFAULT '' NOT NULL, name VARCHAR(255) NOT NULL, json LONGTEXT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_F545EE43DE12AB56 (created_by), INDEX IDX_F545EE4316FE72E1 (updated_by), UNIQUE INDEX uniq_idx (scope, name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE sub_category (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, category_id BIGINT NOT NULL, is_active TINYINT(1) DEFAULT '0', name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_BCE3F798DE12AB56 (created_by), INDEX IDX_BCE3F79816FE72E1 (updated_by), INDEX IDX_BCE3F79812469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE category (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0', name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_64C19C15E237E06 (name), INDEX IDX_64C19C1DE12AB56 (created_by), INDEX IDX_64C19C116FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE country (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0' NOT NULL, name VARCHAR(255) NOT NULL, iso_code VARCHAR(2) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_5373C9665E237E06 (name), UNIQUE INDEX UNIQ_5373C96662B6A45E (iso_code), INDEX IDX_5373C966DE12AB56 (created_by), INDEX IDX_5373C96616FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE exception_log (id BIGINT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, msg LONGTEXT NOT NULL, trace LONGTEXT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE campaign (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, client_id BIGINT NOT NULL, is_active TINYINT(1) DEFAULT '0', name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_1F1512DD5E237E06 (name), INDEX IDX_1F1512DDDE12AB56 (created_by), INDEX IDX_1F1512DD16FE72E1 (updated_by), INDEX IDX_1F1512DD19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE client (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0', name VARCHAR(255) NOT NULL, account_name VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, email_address VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_C74404555E237E06 (name), INDEX IDX_C7440455DE12AB56 (created_by), INDEX IDX_C744045516FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE extraction_template (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0', name VARCHAR(255) NOT NULL, template LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_8929F769DE12AB56 (created_by), INDEX IDX_8929F76916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE extraction (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, campaign_id BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0', name VARCHAR(255) NOT NULL, status SMALLINT NOT NULL, quantity INT NOT NULL, filters LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json_array)', payout DOUBLE PRECISION NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_3ADCB5D65E237E06 (name), INDEX IDX_3ADCB5D6DE12AB56 (created_by), INDEX IDX_3ADCB5D616FE72E1 (updated_by), INDEX IDX_3ADCB5D6F639F774 (campaign_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE extractions_leads (extraction_id BIGINT NOT NULL, lead_id BIGINT NOT NULL, INDEX IDX_3D012381F992488A (extraction_id), INDEX IDX_3D01238155458D (lead_id), PRIMARY KEY(extraction_id, lead_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE lead (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, country_id BIGINT NOT NULL, phone VARCHAR(255) NOT NULL, is_mobile TINYINT(1) DEFAULT '0' NOT NULL, in_opposition TINYINT(1) DEFAULT '0' NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_289161CBDE12AB56 (created_by), INDEX IDX_289161CB16FE72E1 (updated_by), INDEX IDX_289161CBF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE county (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_58E2FF255E237E06 (name), INDEX IDX_58E2FF25DE12AB56 (created_by), INDEX IDX_58E2FF2516FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE gender (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_C7470A425E237E06 (name), INDEX IDX_C7470A42DE12AB56 (created_by), INDEX IDX_C7470A4216FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE owner (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, country_id BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0', name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_CF60E67C5E237E06 (name), INDEX IDX_CF60E67CDE12AB56 (created_by), INDEX IDX_CF60E67C16FE72E1 (updated_by), INDEX IDX_CF60E67CF92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE contact (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, lead_id BIGINT NOT NULL, source_id BIGINT NOT NULL, owner_id BIGINT NOT NULL, sub_category_id BIGINT NOT NULL, gender_id BIGINT NOT NULL, district_id BIGINT DEFAULT NULL, county_id BIGINT DEFAULT NULL, parish_id BIGINT DEFAULT NULL, country_id BIGINT NOT NULL, email VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, birthdate DATE NOT NULL, address VARCHAR(255) NOT NULL, postalcode1 INT NOT NULL, postalcode2 INT NOT NULL, ipaddress VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_4C62E638DE12AB56 (created_by), INDEX IDX_4C62E63816FE72E1 (updated_by), INDEX IDX_4C62E63855458D (lead_id), INDEX IDX_4C62E638953C1C61 (source_id), INDEX IDX_4C62E6387E3C61F9 (owner_id), INDEX IDX_4C62E638F7BFE87C (sub_category_id), INDEX IDX_4C62E638708A0E0 (gender_id), INDEX IDX_4C62E638B08FA272 (district_id), INDEX IDX_4C62E63885E73F45 (county_id), INDEX IDX_4C62E6388707B11F (parish_id), INDEX IDX_4C62E638F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE parish (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_DFF9A9785E237E06 (name), INDEX IDX_DFF9A978DE12AB56 (created_by), INDEX IDX_DFF9A97816FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE source (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, owner_id BIGINT DEFAULT NULL, country_id BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0' NOT NULL, name VARCHAR(255) NOT NULL, external_id INT NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_5F8A7F735E237E06 (name), UNIQUE INDEX UNIQ_5F8A7F739F75D7B0 (external_id), INDEX IDX_5F8A7F73DE12AB56 (created_by), INDEX IDX_5F8A7F7316FE72E1 (updated_by), INDEX IDX_5F8A7F737E3C61F9 (owner_id), INDEX IDX_5F8A7F73F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE district (id BIGINT AUTO_INCREMENT NOT NULL, created_by BIGINT DEFAULT NULL, updated_by BIGINT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_31C154875E237E06 (name), INDEX IDX_31C15487DE12AB56 (created_by), INDEX IDX_31C1548716FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE lb_lock_history (id BIGINT NOT NULL, client_id BIGINT DEFAULT NULL, lead_id BIGINT DEFAULT NULL, campaign_id BIGINT DEFAULT NULL, category_id BIGINT DEFAULT NULL, sub_category_id BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0', status SMALLINT NOT NULL, type SMALLINT NOT NULL, expiration_date DATETIME NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_AF13EB0219EB6921 (client_id), INDEX IDX_AF13EB0255458D (lead_id), INDEX IDX_AF13EB02F639F774 (campaign_id), INDEX IDX_AF13EB0212469DE2 (category_id), INDEX IDX_AF13EB02F7BFE87C (sub_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE lb_lock (id BIGINT AUTO_INCREMENT NOT NULL, client_id BIGINT DEFAULT NULL, lead_id BIGINT DEFAULT NULL, campaign_id BIGINT DEFAULT NULL, category_id BIGINT DEFAULT NULL, sub_category_id BIGINT DEFAULT NULL, is_active TINYINT(1) DEFAULT '0', status SMALLINT NOT NULL, type SMALLINT NOT NULL, expiration_date DATETIME NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_88CE4BB619EB6921 (client_id), INDEX IDX_88CE4BB655458D (lead_id), INDEX IDX_88CE4BB6F639F774 (campaign_id), INDEX IDX_88CE4BB612469DE2 (category_id), INDEX IDX_88CE4BB6F7BFE87C (sub_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE fos_user ADD CONSTRAINT FK_957A6479DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE fos_user ADD CONSTRAINT FK_957A647916FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE fos_user_group ADD CONSTRAINT FK_583D1F3EA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id);
ALTER TABLE fos_user_group ADD CONSTRAINT FK_583D1F3EFE54D947 FOREIGN KEY (group_id) REFERENCES fos_group (id);
ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EBDE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EB16FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE advanced_configuration ADD CONSTRAINT FK_F545EE43DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE advanced_configuration ADD CONSTRAINT FK_F545EE4316FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE sub_category ADD CONSTRAINT FK_BCE3F798DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE sub_category ADD CONSTRAINT FK_BCE3F79816FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE sub_category ADD CONSTRAINT FK_BCE3F79812469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT;
ALTER TABLE category ADD CONSTRAINT FK_64C19C1DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE category ADD CONSTRAINT FK_64C19C116FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE country ADD CONSTRAINT FK_5373C966DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE country ADD CONSTRAINT FK_5373C96616FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DDDE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DD16FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DD19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT;
ALTER TABLE client ADD CONSTRAINT FK_C7440455DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE client ADD CONSTRAINT FK_C744045516FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE extraction_template ADD CONSTRAINT FK_8929F769DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE extraction_template ADD CONSTRAINT FK_8929F76916FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE extraction ADD CONSTRAINT FK_3ADCB5D6DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE extraction ADD CONSTRAINT FK_3ADCB5D616FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE extraction ADD CONSTRAINT FK_3ADCB5D6F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE RESTRICT;
ALTER TABLE extractions_leads ADD CONSTRAINT FK_3D012381F992488A FOREIGN KEY (extraction_id) REFERENCES extraction (id);
ALTER TABLE extractions_leads ADD CONSTRAINT FK_3D01238155458D FOREIGN KEY (lead_id) REFERENCES lead (id);
ALTER TABLE lead ADD CONSTRAINT FK_289161CBDE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE lead ADD CONSTRAINT FK_289161CB16FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE lead ADD CONSTRAINT FK_289161CBF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE RESTRICT;
ALTER TABLE county ADD CONSTRAINT FK_58E2FF25DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE county ADD CONSTRAINT FK_58E2FF2516FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE gender ADD CONSTRAINT FK_C7470A42DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE gender ADD CONSTRAINT FK_C7470A4216FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE owner ADD CONSTRAINT FK_CF60E67CDE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE owner ADD CONSTRAINT FK_CF60E67C16FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE owner ADD CONSTRAINT FK_CF60E67CF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E638DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E63816FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E63855458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E638953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E6387E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E638F7BFE87C FOREIGN KEY (sub_category_id) REFERENCES sub_category (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E638708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E638B08FA272 FOREIGN KEY (district_id) REFERENCES district (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E63885E73F45 FOREIGN KEY (county_id) REFERENCES county (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E6388707B11F FOREIGN KEY (parish_id) REFERENCES parish (id) ON DELETE RESTRICT;
ALTER TABLE contact ADD CONSTRAINT FK_4C62E638F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE RESTRICT;
ALTER TABLE parish ADD CONSTRAINT FK_DFF9A978DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE parish ADD CONSTRAINT FK_DFF9A97816FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7316FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE source ADD CONSTRAINT FK_5F8A7F737E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) ON DELETE RESTRICT;
ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE RESTRICT;
ALTER TABLE district ADD CONSTRAINT FK_31C15487DE12AB56 FOREIGN KEY (created_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE district ADD CONSTRAINT FK_31C1548716FE72E1 FOREIGN KEY (updated_by) REFERENCES fos_user (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock_history ADD CONSTRAINT FK_AF13EB0219EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock_history ADD CONSTRAINT FK_AF13EB0255458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock_history ADD CONSTRAINT FK_AF13EB02F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock_history ADD CONSTRAINT FK_AF13EB0212469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock_history ADD CONSTRAINT FK_AF13EB02F7BFE87C FOREIGN KEY (sub_category_id) REFERENCES sub_category (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock ADD CONSTRAINT FK_88CE4BB619EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock ADD CONSTRAINT FK_88CE4BB655458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock ADD CONSTRAINT FK_88CE4BB6F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock ADD CONSTRAINT FK_88CE4BB612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT;
ALTER TABLE lb_lock ADD CONSTRAINT FK_88CE4BB6F7BFE87C FOREIGN KEY (sub_category_id) REFERENCES sub_category (id) ON DELETE RESTRICT;

CREATE TABLE `leadcentre_contacts` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `contact_id` bigint(20) NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `gender` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `firstname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `lastname` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `birthdate` date NOT NULL,
  `phone` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `address` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `country` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `postalcode1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `postalcode2` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `city` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `district` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `county` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `parish` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ipaddress` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `source_page_id` int(11) NOT NULL,
  `source_page_domain` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `category` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `extra_fields` text COLLATE utf8_unicode_ci NOT NULL,
  `is_processed` tinyint(1) NOT NULL DEFAULT '0',
  `resting_time`
  PRIMARY KEY (`id`),
  KEY `phone` (`phone`),
  KEY `postalcode1` (`postalcode1`),
  KEY `postalcode2` (`postalcode2`),
  KEY `source_page_id` (`source_page_id`),
  KEY `email` (`email`),
  KEY `country` (`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
