services:
  base:
    class: ListBroking\AppBundle\Service\Base\BaseService
    abstract: true
    calls:
      - [setEntityManager, [@doctrine.orm.entity_manager]]
      - [setDoctrineCache, [@doctrine_cache.providers.memcached_query_cache]]
      - [setFormFactory, [@form.factory]]
      - [setLogger, [@logger]]
      - [setTokenStorage, [@security.token_storage]]
    tags:
      - { name: monolog.logger, channel: app_services }

  messaging:
    class: ListBroking\AppBundle\Service\Helper\MessagingService
    arguments: [@service_container]

  file_handler:
    class: ListBroking\AppBundle\Service\Helper\FileHandlerService
    arguments: [@kernel, @oneup_flysystem.aws_s3_filesystem]

  app:
    class: ListBroking\AppBundle\Service\Helper\AppService
    parent: base
    arguments: [@mailer, @swiftmailer.spool, @swiftmailer.transport.real, @twig]

  statistics:
    class: ListBroking\AppBundle\Service\Helper\StatisticsService
    parent: base

  extraction:
    class: ListBroking\AppBundle\Service\BusinessLogic\ExtractionService
    parent: base
    arguments: [@request_stack, @filter_engine ]

  staging:
    class: ListBroking\AppBundle\Service\BusinessLogic\StagingService
    parent: base
    arguments: [@validator_engine]