services:
  app.consumer.run_extraction:
    class: ListBroking\AppBundle\Consumer\RunExtractionConsumer
    arguments: ["@app.service.extraction", "@logger", "@listbroking.app.monolog.processor.service_log_task_identifier"]
    tags:
        - { name: monolog.logger, channel: service }

  app.consumer.deduplicate_extraction:
    class: ListBroking\AppBundle\Consumer\DeduplicateExtractionConsumer
    arguments: ["@app.service.extraction", "@file_handler", "@logger", "@listbroking.app.monolog.processor.service_log_task_identifier"]
    tags:
        - { name: monolog.logger, channel: service }

  app.consumer.lock_extraction:
    class: ListBroking\AppBundle\Consumer\LockExtractionConsumer
    arguments: ["@app.service.extraction", "@logger", "@listbroking.app.monolog.processor.service_log_task_identifier"]
    tags:
        - { name: monolog.logger, channel: service }

  app.consumer.deliver_extraction:
    class: ListBroking\AppBundle\Consumer\DeliverExtractionConsumer
    arguments: ["@app", "@app.service.extraction", "@file_handler", "@logger", "@listbroking.app.monolog.processor.service_log_task_identifier"]
    tags:
        - { name: monolog.logger, channel: service }

  app.consumer.opposition_list_import:
    class: ListBroking\AppBundle\Consumer\OppositionListImportConsumer
    arguments: ["@messaging", "@app.service.staging", "@file_handler", "@logger", "@listbroking.app.monolog.processor.service_log_task_identifier"]
    tags:
        - { name: monolog.logger, channel: service }

  app.consumer.staging_contact_import:
    class: ListBroking\AppBundle\Consumer\StagingContactImportConsumer
    arguments: ["@messaging", "@app.service.staging", "@file_handler", "@logger", "@listbroking.app.monolog.processor.service_log_task_identifier"]
    tags:
        - { name: monolog.logger, channel: service }
