services:
  app.consumer.run_extraction:
    class: ListBroking\AppBundle\Consumer\RunExtractionConsumer
    arguments: [@extraction]

  app.consumer.deduplicate_extraction:
    class: ListBroking\AppBundle\Consumer\DeduplicateExtractionConsumer
    arguments: [@extraction]

  app.consumer.lock_extraction:
    class: ListBroking\AppBundle\Consumer\LockExtractionConsumer
    arguments: [@extraction]

  app.consumer.deliver_extraction:
    class: ListBroking\AppBundle\Consumer\DeliverExtractionConsumer
    arguments: [@app, @extraction, @file_handler]

  app.consumer.opposition_list_import:
    class: ListBroking\AppBundle\Consumer\OppositionListImportConsumer
    arguments: [@messaging, @staging, @file_handler]

  app.consumer.staging_contact_import:
    class: ListBroking\AppBundle\Consumer\StagingContactImportConsumer
    arguments: [@messaging, @staging, @file_handler]