services:
    app.controller.api:
        class: ListBroking\AppBundle\Controller\APIController
        arguments:
            - '@logger'
            - '@app.service.staging'
            - '@app.service.extraction'
            - '@app.authentication.fos_user'

    app.controller.webhook:
        class: ListBroking\AppBundle\Controller\WebhookController
        arguments:
            - '@logger'
            - '@app.service.staging'
            - '@app.validation.webhook_request_handler'
            - '@app.authentication.fos_user'
