services:
  listbroking.appbundle.filters.form:
    class:  ListBroking\AppBundle\Form\FiltersType
    arguments: [@app]
    tags:
      - { name: form.type, alias: filters }

  listbroking.appbundle.extraction_deduplication.from:
    class: ListBroking\AppBundle\Form\ExtractionDeduplicationType
    tags:
      - { name: form.type, alias: extraction_deduplication }

  listbroking.appbundle.extraction_locking.from:
    class: ListBroking\AppBundle\Form\ExtractionLockingType
    tags:
      - { name: form.type, alias: extraction_locking }

  listbroking.appbundle.opposition_list_import.form.type:
    class: ListBroking\AppBundle\Form\OppositionListImportType
    arguments: [@app]
    tags:
      - { name: form.type, alias: opposition_list_import }

  listbroking.appbundle.staging_contact_import.form.type:
    class: ListBroking\AppBundle\Form\StagingContactImportType
    tags:
      - { name: form.type, alias: staging_contact_import }

  listbroking.appbundle.data_card_filter.form.type:
    class: ListBroking\AppBundle\Form\DataCardFilterType
    tags:
      - { name: form.type, alias: data_card_filter }