services:
  listbroking.ajax_authentication_exception_listener:
    class: ListBroking\AppBundle\EventListener\AjaxAuthenticationExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1000 }

  listbroking.ajax_authentication_handler_listener:
    class: ListBroking\AppBundle\EventListener\AjaxAuthenticationHandlerListener
    arguments:
      - "@router"
      - "@session"

  listbroking.flush_listener:
    class: ListBroking\AppBundle\EventListener\FlushListener
    arguments: ["@doctrine_cache.providers.memcached_query_cache"]
    tags:
        - { name: doctrine.event_listener, event: onFlush }