services:
    listbroking.app.monolog.formatter.compactformat:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "%%datetime%%|%%extra.task_identifier%%|%%channel%%|%%level_name%%|M: %%message%%|%%context%%|\n"

    listbroking.app.monolog.processor.service_log_task_identifier:
        class: ListBroking\AppBundle\Monolog\Processor\ServiceLogTaskIdentifier

    listbroking.app.monolog.processor.service_log:
        class: ListBroking\AppBundle\Monolog\Processor\ServiceLogProcessor
        calls:
            - [setServiceLogTaskIdentifier, ["@listbroking.app.monolog.processor.service_log_task_identifier"]]
        tags:
            - { name: monolog.processor, method: processRecord }
