services:
  guzzle.client:
      class: %guzzle.client.class%
      tags:
          - { name: "guzzle.client" }

  filter_engine:
    class: ListBroking\AppBundle\Engine\FilterEngine
    arguments:
      entityManager: @doctrine.orm.entity_manager

  validator_engine:
    class: ListBroking\AppBundle\Engine\ValidatorEngine
    arguments: [@doctrine, @guzzle.client]