services:
  guzzle.client:
      class: Guzzle\Service\Client

  filter_engine:
    class: ListBroking\AppBundle\Engine\FilterEngine
    arguments: ["@doctrine.orm.entity_manager"]

  validator_engine:
    class: ListBroking\AppBundle\Engine\ValidatorEngine
    arguments: ["@doctrine", "@guzzle.client", "@app"]
