services:
  base:
    class: ListBroking\AppBundle\Service\Base\BaseService
    abstract: true
    calls:
      - [setEntityManager, ["@doctrine.orm.entity_manager"]]
      - [setDoctrineCache, ["@doctrine_cache.providers.query_cache"]]
      - [setFormFactory, ["@form.factory"]]
      - [setLogger, ["@logger"]]
      - [setTokenStorage, ["@security.token_storage"]]
    tags:
      - { name: monolog.logger, channel: service }

  messaging:
    class: ListBroking\AppBundle\Service\Helper\MessagingService
    arguments: ["@service_container"]

  file_handler:
    class: ListBroking\AppBundle\Service\Helper\FileHandlerService
    arguments:
      projectRootDir: "%kernel.root_dir%"
      zipService:     "@adclick.components.service.zip"

  app:
    class: ListBroking\AppBundle\Service\Helper\AppService
    parent: base
    arguments: ["@swiftmailer.mailer", "@twig"]

  app.service.statistics:
    class: ListBroking\AppBundle\Service\Helper\StatisticsService
    parent: base
    arguments:
        - "@app.repository.contact"
        - "@app.repository.audiences_stats"

  app.service.extraction:
    class: ListBroking\AppBundle\Service\BusinessLogic\ExtractionService
    parent: base
    arguments:
        - "@request_stack"
        - "@filter_engine"
        - "@messaging"
        - "@app.repository.extraction"
        - "@app.repository.campaign"
        - "@app.repository.gender"
        - "@app.repository.district"
        - "@app.repository.sub_category"
        - "@app.repository.extraction_contact"

  app.service.staging:
    class: ListBroking\AppBundle\Service\BusinessLogic\StagingService
    parent: base
    arguments:
        - "@validator_engine"
        - "@app.service.factory.opposition_list"
        - "@validator"
        - "@app.repository.opposition_list"
        - "@app.repository.staging_contact"
        - "@app.repository.lead"
        - "@app.repository.source"
        - "@app.service.contact_obfuscation"

  app.service.extraction_contact:
    class: ListBroking\AppBundle\Service\BusinessLogic\ExtractionContactService
    arguments:
        - "@app.repository.extraction_contact"

  hurry:
    class: ListBroking\AppBundle\Service\External\HurryService
    arguments: [ "%hurry_api_url%", "%hurry_api_token%", "@logger" ]

  app.service.contact_obfuscation:
    class: ListBroking\AppBundle\Service\BusinessLogic\ContactObfuscationService
    parent: base
    arguments:
        - "@app.repository.extraction_deduplication"
        - "@app.repository.opposition_list"
        - "@app.repository.staging_contact"
        - "@app.repository.staging_contact_processed"
        - "@app.repository.staging_contact_dqp"
        - "%email_invalid_domain%"

  app.service.client_notification:
    class: ListBroking\AppBundle\Service\BusinessLogic\ClientNotificationService
    parent: base
    arguments:
        - "@app.repository.client"
        - "@app.repository.extraction_contact"
        - "@app.factory.client_notification"
        - "@adclick.components.mailer_gdpr"

  app.service.lead:
    class: ListBroking\AppBundle\Service\BusinessLogic\LeadService
    arguments:
        - "@app.repository.lead"
        - "@app.repository.lead_hist"
        - "@app.repository.contact"
        - "@app.repository.contact_hist"

  app.service.campaign:
    class: ListBroking\AppBundle\Service\BusinessLogic\CampaignService
    parent: base
    arguments:
        - "@app.repository.campaign"
        - "@app.repository.client"
        - "@hurry"
