services:
    app.controller.api:
        class: ListBroking\AppBundle\Controller\APIController
        arguments:
            - '@logger'
            - '@app.service.staging'
            - '@app.service.extraction'
            - '@app.service.extraction_contact'
            - '@app.authentication.fos_user'
            - '@app.service.contact_obfuscation'
            - '@app.service.lead'
            - '@app.service.client_notification'
            - '@app.service.campaign'
            - '@app.service.statistics'

    app.controller.webhook:
        class: ListBroking\AppBundle\Controller\WebhookController
        arguments:
            - '@logger'
            - '@app.service.staging'
            - '@app.validation.webhook_request_handler'
            - '@app.authentication.fos_user'
