services:
  app.service.factory.lead:
    class: ListBroking\AppBundle\Service\Factory\LeadFactory

  app.service.factory.opposition_list:
    class: ListBroking\AppBundle\Service\Factory\OppositionListFactory

  app.factory.client_notification:
    class: ListBroking\AppBundle\Service\Factory\ClientNotificationFactory

  app.factory.consent_revalidation:
    class: ListBroking\AppBundle\Service\Factory\ConsentRevalidationFactory
