services:
    app.repository.opposition_list:
        class: ListBroking\AppBundle\Repository\OppositionListRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\OppositionList'

    app.repository.staging_contact:
        class: ListBroking\AppBundle\Repository\StagingContactRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\StagingContact'

    app.repository.lead:
        class: ListBroking\AppBundle\Repository\LeadRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\Lead'

    app.repository.lead_hist:
        class: ListBroking\AppBundle\Repository\LeadHistRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\LeadHist'

    app.repository.source:
        class: ListBroking\AppBundle\Repository\SourceRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\Source'

    app.repository.extraction:
        class: ListBroking\AppBundle\Repository\ExtractionRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\Extraction'

    app.repository.extraction_contact:
        class: ListBroking\AppBundle\Repository\ExtractionContactRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\ExtractionContact'

    app.repository.extraction_contact_hist:
        class: ListBroking\AppBundle\Repository\ExtractionContactHistRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\ExtractionContactHist'

    app.repository.contact:
        class: ListBroking\AppBundle\Repository\ContactRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\Contact'

    app.repository.contact_hist:
        class: ListBroking\AppBundle\Repository\ContactHistRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\ContactHist'

    app.repository.extraction_deduplication:
        class: ListBroking\AppBundle\Repository\ExtractionContactRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\ExtractionDeduplication'

    app.repository.staging_contact_processed:
        class: ListBroking\AppBundle\Repository\StagingContactProcessedRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\StagingContactProcessed'

    app.repository.staging_contact_dqp:
        class: ListBroking\AppBundle\Repository\StagingContactDQPRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\StagingContactDQP'

    app.repository.client:
        class: ListBroking\AppBundle\Repository\ClientRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\Client'

    app.repository.campaign:
        class: ListBroking\AppBundle\Repository\CampaignRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\Campaign'

    app.repository.audiences_stats:
        class: ListBroking\AppBundle\Repository\AudiencesStatsRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\AudiencesStats'

    app.repository.gender:
        class: ListBroking\AppBundle\Repository\GenderRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - 'ListBroking\AppBundle\Entity\Gender'
