services:
  guzzle.client:
      class: Guzzle\Service\Client

  filter_engine:
    class: ListBroking\AppBundle\Engine\FilterEngine
    arguments: ["@doctrine.orm.entity_manager"]

  validator_engine:
    class: ListBroking\AppBundle\Engine\ValidatorEngine
    arguments: ["@doctrine", "@guzzle.client", "@app", "@logger"]

  app.authentication.fos_user:
    class: ListBroking\AppBundle\Service\Authentication\FosUserAuthenticationService
    arguments:
      - '@fos_user.user_manager.default'

  app.service.consent_revalidation:
    class: ListBroking\AppBundle\Service\BusinessLogic\ConsentRevalidationService
    arguments:
      - '@app.repository.contact'
      - '@app.repository.consent_revalidation'
      - '@app.repository.configuration'
      - '@app.factory.consent_revalidation'
      - '@app.service.external.twilio'
      - '@app.service.external.phone_number'
      - '@app.service.external.integromat'
      - '@router'
      - '@logger'
      - '%twilio_revalidation_flow_id%'
      - '%twilio_revalidation_phone_number%'
      - '%twilio_database_username%'
      - '%twilio_database_token%'

  app.service.external.twilio:
    class: ListBroking\AppBundle\Service\External\TwilioService
    arguments:
      - '@app.factory.twilio_client'
      - '@logger'

  app.service.external.phone_number:
    class: ListBroking\AppBundle\Service\External\PhoneNumberService

  app.service.external.integromat:
    class: ListBroking\AppBundle\Service\External\IntegromatService
    arguments:
      - '@guzzle.client'
      - '@logger'
      - '%integromat_iuris_webhook%'
