ListBroking\AppBundle\Entity\Brand:
    type: entity
    table: brand
    repositoryClass: ListBroking\AppBundle\Repository\BrandRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        ivrAudioUrl:
            type: string
            length: 255
            nullable: true
            column: ivr_audio_url
        createdAt:
            type:   datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type:   datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        sources:
            targetEntity: ListBroking\AppBundle\Entity\Source
            mappedBy:     brand
    lifecycleCallbacks: {  }
