ListBroking\AppBundle\Entity\Source:
    type: entity
    table: source
    repositoryClass: ListBroking\AppBundle\Repository\SourceRepository
    id:
        id:
            type: bigint
            id:   true
            generator:
                strategy: AUTO
    fields:
        name:
            type:   string
            column: name
        external_id:
            type:     string
            column:   external_id
            nullable: false
            unique:   true
# Timestampable
        created_at:
            type:     datetime
            nullable: true
            gedmo:    { timestampable: { on: create } }

        updated_at:
            type:     datetime
            nullable: true
            gedmo:    { timestampable: { on: update } }
# End of Timestampable
    manyToOne:
        owner:
            targetEntity: ListBroking\AppBundle\Entity\Owner
            inversedBy:   sources
            joinColumn:
                name:                 owner_id
                referencedColumnName: id
                onDelete:             restrict
        country:
            targetEntity: ListBroking\AppBundle\Entity\Country
            joinColumn:
                name:                 country_id
                referencedColumnName: id
                onDelete:             restrict
        brand:
            targetEntity: ListBroking\AppBundle\Entity\Brand
            joinColumn:
                name:                 brand_id
                referencedColumnName: id
                onDelete:             'SET NULL'
    oneToMany:
        contacts:
            targetEntity: ListBroking\AppBundle\Entity\Contact
            mappedBy:     source
            cascade:      [all]
