services:
  listbroking.exceptionhandler.exception_listener:
    class: ListBroking\ExceptionHandlerBundle\EventListener\ExceptionListener
    arguments: [@doctrine.orm.entity_manager, @mailer, @twig]
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  listbroking.exceptionhandler.admin.exception_log:
    class: ListBroking\ExceptionHandlerBundle\Admin\ExceptionLogAdmin
    arguments: [~, ListBroking\ExceptionHandlerBundle\Entity\ExceptionLog, SonataAdminBundle:CRUD]
    tags:
      - {name: sonata.admin, manager_type: orm, group: Main, label: ExceptionLog}
