services:
#    listbroking.exceptionhandler.exception_listener:
#        class: ListBroking\ExceptionHandlerBundle\EventListener\ExceptionListener
#        arguments: [@doctrine.orm.entity_manager, @mailer, @twig]
#        tags:
#             - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }