parameters:
    listbroking.lockbundle.lock.entity.name: ListBrokingLockBundle:Lock
    listbroking.lockbundle.lock.entity.class: ListBroking\LockBundle\Entity\Lock
    listbroking.lockbundle.lock.repository.class: ListBroking\LockBundle\Repository\ORM\LockRepository

    listbroking.lockbundle.lock_history.entity.name: ListBrokingLockBundle:LockHistory
    listbroking.lockbundle.lock_history.entity.class: ListBroking\LockBundle\Entity\LockHistory
    listbroking.lockbundle.lock_history.repository.class: ListBroking\LockBundle\Repository\ORM\LockHistoryRepository

    listbroking.lockbundle.engine.class: ListBroking\LockBundle\Engine\LockEngine
    listbroking.lockbundle.service.class: ListBroking\LockBundle\Service\LockService
    listbroking.lockbundle.rotate.command.class: ListBroking\LockBundle\Command\RotateExpiredLocksCommand

    listbroking.lockbundle.json.form.type.class: ListBroking\LockBundle\Form\Type\JsonType
    listbroking.lockbundle.filters.form.class: ListBroking\LockBundle\Form\FiltersForm

services:
    listbroking.lockbundle.lock.repository:
        class: %listbroking.lockbundle.lock.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.lockbundle.lock.entity.name%
            alias: lloc
            entityClass: %listbroking.lockbundle.lock.entity.class%
            inflector: @inflector.tool

    listbroking.lockbundle.lock_history.repository:
        class: %listbroking.lockbundle.lock_history.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.lockbundle.lock_history.entity.name%
            alias: lloc_hist
            entityClass: %listbroking.lockbundle.lock_history.entity.class%
            inflector: @inflector.tool

    listbroking.lock.service:
        class: %listbroking.lockbundle.service.class%
        arguments: [@listbroking.lockbundle.lock.repository, @listbroking.leadbundle.lead.repository, @listbroking.leadbundle.contact.repository]

    listbroking.lock.rotate.command:
        class: %listbroking.lockbundle.rotate.command.class%
        arguments: [@listbroking.advanced_configuration.service, @listbroking.lock.service]
        tags:
          - { name: console.command, alias: rotate_logs }


    listbroking.lockbundle.filters.form:
        class:  %listbroking.lockbundle.filters.form.class%
        arguments: [@listbroking.core.service, @listbroking.contact.service, @listbroking.client.service ]
        tags:
          - { name: form.type, alias: filters }

    listbroking.lockbundle.json.form.type:
        class: %listbroking.lockbundle.json.form.type.class%
        tags:
          - { name: form.type, alias: json }