parameters:
    listbroking.lockbundle.lock.entity.name: ListBrokingLockBundle:Lock
    listbroking.lockbundle.lock.entity.class: ListBroking\LockBundle\Entity\Lock
    listbroking.lockbundle.lock.repository.class: ListBroking\LockBundle\Repository\ORM\LockRepository

    listbroking.lockbundle.lock_history.entity.name: ListBrokingLockBundle:LockHistory
    listbroking.lockbundle.lock_history.entity.class: ListBroking\LockBundle\Entity\LockHistory
    listbroking.lockbundle.lock_history.repository.class: ListBroking\LockBundle\Repository\ORM\LockHistoryRepository

    listbroking.lock.engine.class: ListBroking\LockBundle\Engine\LockEngine
    listbroking.lock.service.class: ListBroking\LockBundle\Service\LockService
    listbroking.lock.rotate.command.class: ListBroking\LockBundle\Command\RotateExpiredLocksCommand

services:
    listbroking.lockbundle.lock.repository:
        class: %listbroking.lockbundle.lock.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.lockbundle.lock.entity.name%
            alias: lloc
            entityClass: %listbroking.lockbundle.lock.entity.class%
            inflector: @inflector.tool

    listbroking.lockbundle.lock_history.repository:
        class: %listbroking.lockbundle.lock_history.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.lockbundle.lock_history.entity.name%
            alias: lloc_hist
            entityClass: %listbroking.lockbundle.lock_history.entity.class%
            inflector: @inflector.tool

    listbroking.lock.service:
        class: %listbroking.lock.service.class%
        arguments: [@listbroking.lockbundle.lock.repository, @listbroking.leadbundle.lead.repository, @listbroking.leadbundle.contact.repository]

    listbroking.lock.rotate.command:
        class: %listbroking.lock.rotate.command.class%
        arguments: [@listbroking.advanced_configuration.service, @listbroking.lock.service]
        tags:
          - { name: console.command, alias: rotate_logs }