parameters:
    listbroking.lockbundle.lock.entity.name: ListBrokingLockBundle:Lock
    listbroking.lockbundle.lock.entity.class: ListBroking\LockBundle\Entity\Lock
    listbroking.lockbundle.lock.repository.class: ListBroking\LockBundle\Repository\ORM\LockRepository

    listbroking.lock.engine.class: ListBroking\LockBundle\Engine\LockEngine

    listbroking.lock.service.class: ListBroking\LockBundle\Service\LockService


services:
    listbroking.lockbundle.lock.repository:
        class: %listbroking.lockbundle.lock.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.lockbundle.lock.entity.name%
            alias: lloc
            entityClass: %listbroking.lockbundle.lock.entity.class%
            inflector: @inflector.tool

    listbroking.lock.service:
        class: %listbroking.lock.service.class%
        arguments: [@listbroking.lockbundle.lock.repository]