ListBroking\LeadBundle\Entity\Contact:
    type:   entity
    table:  contact
    id:
        id:
            type: bigint
            id:   true
            generator:
                strategy: AUTO
    fields:
        email:
            type:   string
            column: email
        firstname:
            type:   string
            column: firstname
        lastname:
            type:   string
            column: lastname
        birthdate:
            type:   date
            column: birthdate
        address:
            type:   string
            column: address
        postalcode1:
            type:   integer
            column: postalcode1
        postalcode2:
            type:   integer
            column: postalcode2
        ipaddress:
            type:   string
            column: ipaddress
# Timestampable
        created_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: create } }

        updated_at:
            type: datetime
            nullable: true
            gedmo: { timestampable: { on: update } }
# End of Timestampable

# Blameable
    manyToOne:
        created_by:
            targetEntity: Adclick\UserBundle\Entity\User
            joinColumn:
                name: created_by
                referencedColumnName: id
                onDelete: restrict
            gedmo: { blameable: { on: create } }

        updated_by:
            targetEntity: Adclick\UserBundle\Entity\User
            joinColumn:
                name: updated_by
                referencedColumnName: id
                onDelete: restrict
            gedmo: { blameable: { on: update } }
# End of blameable
        lead:
            targetEntity: ListBroking\LeadBundle\Entity\Lead
            inversedBy:   leads
            joinColumn:
                name:                 lead_id
                referencedColumnName: id
                onDelete:             restrict
                nullable:             false
        source:
            targetEntity: ListBroking\LeadBundle\Entity\Source
            inversedBy:   sources
            joinColumn:
                name:                 source_id
                referencedColumnName: id
                onDelete:             restrict
                nullable:             false
        owner:
            targetEntity: ListBroking\LeadBundle\Entity\Owner
            inversedBy:   owners
            joinColumn:
                name:                 owner_id
                referencedColumnName: id
                onDelete:             restrict
                nullable:             false
        sub_category:
              targetEntity: ListBroking\CoreBundle\Entity\SubCategory
              inversedBy:   sub_categories
              joinColumn:
                  name:                 sub_category_id
                  referencedColumnName: id
                  onDelete:             restrict
                  nullable:             false
        gender:
              targetEntity: ListBroking\LeadBundle\Entity\Gender
              inversedBy:   genders
              joinColumn:
                  name:                 gender_id
                  referencedColumnName: id
                  onDelete:             restrict
                  nullable:             false
        district:
              targetEntity: ListBroking\LeadBundle\Entity\District
              inversedBy:   districts
              joinColumn:
                  name:                 district_id
                  referencedColumnName: id
                  onDelete:             restrict
                  nullable:             false
        county:
              targetEntity: ListBroking\LeadBundle\Entity\County
              inversedBy:   counties
              joinColumn:
                  name:                 county_id
                  referencedColumnName: id
                  onDelete:             restrict
                  nullable:             false
        parish:
              targetEntity: ListBroking\LeadBundle\Entity\Parish
              inversedBy:   parishes
              joinColumn:
                  name:                 parish_id
                  referencedColumnName: id
                  onDelete:             restrict
                  nullable:             false
        country:
              targetEntity: ListBroking\LeadBundle\Entity\Country
              inversedBy:   countries
              joinColumn:
                  name:                 country_id
                  referencedColumnName: id
                  onDelete:             restrict
                  nullable:             false