# Used to expose routing to the client-side code
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

dashboard_index:
    path: /
    defaults: { _controller: ListBrokingUIBundle:Dashboard:index }

extraction_index:
    path: /extraction/wizard
    defaults: { _controller: ListBrokingUIBundle:Extraction:index }

extraction_configuration:
    path: /extraction/wizard/configuration-1
    defaults: { _controller: ListBrokingUIBundle:Extraction:configuration }

extraction_filtering:
    path: /extraction/wizard/{extraction_id}/filtering-2
    defaults: { _controller: ListBrokingUIBundle:Extraction:filtering }
    options:
        expose: true

extraction_download:
    path: /extraction/wizard/{extraction_id}/download-3/{extraction_template_id}
    defaults: { _controller: ListBrokingUIBundle:Extraction:extractionDownload }
    options:
        expose: true

lead_deduplication:
    path: /extraction/wizard/{extraction_id}/deduplication-4
    defaults: { _controller: ListBrokingUIBundle:Extraction:leadDeduplication }

ajax_count_leads:
    path: /ajax/count/leads
    defaults: { _controller: ListBrokingUIBundle:Ajax:countLeads }
    options:
        expose: true

ajax_lists:
    path: /ajax/lists
    defaults: { _controller: ListBrokingUIBundle:Ajax:lists }
    options:
        expose: true

ajax_form_submit:
    path: /ajax/form/submit/{form_name}
    defaults: { _controller: ListBrokingUIBundle:Ajax:formSubmission }
    options:

ajax_extraction_exclude_lead:
    path: /ajax/extraction/{extraction_id}/lead/{lead_id}/exclude
    defaults: { _controller: ListBrokingUIBundle:Ajax:extractionExcludeLead }
    options:
        expose: true
    requirements:
          extraction_id: \d+
          lead_id: \d+

homepage:
    path:     /
    defaults: { _controller: ListBrokingUIBundle:Default:index }
