parameters:
    listbroking.uibundle.service.class: ListBroking\UIBundle\Service\UIService

    listbroking.uibundle.dashboard.controller.class: ListBroking\UIBundle\Controller\DashboardController
    listbroking.uibundle.extraction.controller.class: ListBroking\UIBundle\Controller\ExtractionController
    listbroking.uibundle.ajax.controller.class: ListBroking\UIBundle\Controller\AjaxController

services:
    listbroking.uibundle.service:
        class: %listbroking.uibundle.service.class%
        arguments:
            - @listbroking.client.service
            - @listbroking.extraction.service
            - @listbroking.lead.service
            - @form.factory
            - @security.csrf.token_manager


    listbroking.uibundle.dashboard.controller:
        class: %listbroking.uibundle.dashboard.controller.class%
        arguments: [@router, @twig]

    listbroking.uibundle.extraction.controller:
        class: %listbroking.uibundle.extraction.controller.class%
        arguments: [@twig, @router, @listbroking.extraction.service, @listbroking.uibundle.service]

    listbroking.uibundle.ajax.controller:
        class: %listbroking.uibundle.ajax.controller.class%
        arguments: [@listbroking.uibundle.service]

