parameters:
    listbroking.uibundle.form.type.class: ListBroking\UIBundle\Form\Type\CountryFormType

services:
    listbroking.uibundle.form.type:
        class:  %listbroking.uibundle.form.type.class%
        tags:
          - { name: form.type, alias: country_form }
