parameters:
    listbroking.clientbundle.client.entity.name: ListBrokingClientBundle:Client
    listbroking.clientbundle.client.entity.class: ListBroking\ClientBundle\Entity\Client
    listbroking.clientbundle.client.repository.class: ListBroking\ClientBundle\Repository\ORM\ClientRepository

    listbroking.clientbundle.campaign.entity.name: ListBrokingClientBundle:Campaign
    listbroking.clientbundle.campaign.entity.class: ListBroking\ClientBundle\Entity\Campaign
    listbroking.clientbundle.campaign.repository.class: ListBroking\ClientBundle\Repository\ORM\CampaignRepository

    listbroking.client.service.class: ListBroking\ClientBundle\Service\ClientService

services:
    listbroking.clientbundle.client.repository:
        class: %listbroking.clientbundle.client.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.clientbundle.client.entity.name%
            alias: cli
            entityClass: %listbroking.clientbundle.client.entity.class%
            inflector: @inflector.tool
    listbroking.clientbundle.campaign.repository:
        class: %listbroking.clientbundle.campaign.repository.class%
        arguments:
            entityManager: @doctrine.orm.default_entity_manager
            entityName: %listbroking.clientbundle.campaign.entity.name%
            alias: camp
            entityClass: %listbroking.clientbundle.campaign.entity.class%
            inflector: @inflector.tool

    listbroking.client.service:
        class: %listbroking.client.service.class%
        arguments: [@cache, @validator, @listbroking.clientbundle.client.repository, @listbroking.clientbundle.campaign.repository]

