ListBroking\ClientBundle\Entity\Client:
   constraints:
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
           fields:   name
           message:  "Name is duplicated."
ListBroking\ClientBundle\Entity\Campaign:
   constraints:
       - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
           fields:   name
           message:  "Name is duplicated."

