parameters:
    listbroking.advanced_configuration.repository.class: ListBroking\AdvancedConfigurationBundle\Persistence\ORM\AdvancedConfigurationRepository
    listbroking.advanced_configuration.service.class: ListBroking\AdvancedConfigurationBundle\Service\ListBrokingAdvancedConfiguration

services:
    listbroking.advanced_configuration.repository:
        class: %listbroking.advanced_configuration.repository.class%
        arguments:
            entityManager: "@doctrine.orm.default_entity_manager"
            entityName: 'AdclickAdvancedConfigurationBundle:AdvancedConfiguration'
            alias: "lbac"
            entityClass: 'Adclick\AdvancedConfigurationBundle\Entity\AdvancedConfiguration'
            inflector: @inflector.tool
    listbroking.advanced_configuration.service:
        class: %listbroking.advanced_configuration.service.class%
        arguments: [@adclick.advanced_configuration.service]

    # Alias to help injecting the service
    adv_config: @listbroking.advanced_configuration.service